command:
  - uvicorn
  - main:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"

env:
  - name: LAKEBASE_HOST
    value: "ep-autumn-star-d2jzw5xc.database.us-east-1.cloud.databricks.com"
  - name: LAKEBASE_DB
    value: "quest_db"
  - name: QUEST_SQL_WAREHOUSE_ID
    value: "03aad21c886e3333"
